DROP TABLE PhoneBook;
DROP SEQUENCE SEQ_PBNUM;

CREATE TABLE PhoneBook(
    PBNUM NUMBER  CONSTRAINT PBNUMISPRIMARY PRIMARY KEY,
    NAME VARCHAR2(30) CONSTRAINT NAMEISNOTNULL  NOT NULL,
    AGE NUMBER DEFAULT '00',
    ADDRESS VARCHAR2(80)DEFAULT '입력된정보없음',
    PHONE VARCHAR2(11) CONSTRAINT PHONEISNOTNULL NOT NULL
    );
    
    COMMENT ON COLUMN PhoneBook.PBNUM IS '순번';
    COMMENT ON COLUMN PhoneBook.NAME IS '이름';
    COMMENT ON COLUMN PhoneBook.AGE IS '나이';
    COMMENT ON COLUMN PhoneBook.ADDRESS IS '주소';
    COMMENT ON COLUMN PhoneBook.PHONE IS '전화번호';
    
SELECT * FROM phonebook;
    
CREATE SEQUENCE SEQ_PBNUM
NOCACHE;

INSERT INTO phonebook VALUES (SEQ_PBNUM.NEXTVAL,'관리자','00','관리자전용','01000000000');
    